apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httproute-prometheus-shim
rules:
  - apiGroups: ["networking.k8s.io"]
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - apiGroups: ["gateway.networking.k8s.io"]
    resources:
      - httproutes
      - grpcroutes
    verbs:
      - get
      - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httproute-prometheus-shim
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: httproute-prometheus-shim-sd-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: httproute-prometheus-shim
subjects:
  - kind: ServiceAccount
    name: httproute-prometheus-shim
    namespace: default
